;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-char
        backward-kill-sexp
        backward-word
        better-kill-line
        crux-move-beginning-of-line
        delete-horizontal-space
        delete-indentation
        downcase-region
        easy-kill
        easy-mark
        end-of-buffer
        forward-char
        forward-word
        helm-show-kill-ring
        indent-for-tab-command
        keyboard-escape-quit
        kill-to-end-of-sexp
        mark-at-end-or-copy-line
        move-past-close-and-reindent
        next-line
        org-end-of-line
        org-self-insert-command
        self-insert-command
        set-mark-command
        sp-backward-delete-char
        sp-backward-down-sexp
        sp-backward-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-mark-sexp
        sp-splice-sexp
        sp-up-sexp
        undefined
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        indent-region
        mc/keyboard-quit
        ))
