;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-newline
        better-kill-line
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        crux-move-beginning-of-line
        delete-horizontal-space
        delete-indentation
        easy-kill
        easy-mark
        forward-sexp
        keyboard-escape-quit
        kill-sexp
        kill-to-end-of-sexp
        mark-at-end-or-copy-line
        org-forward-element
        org-self-insert-command
        paredit-forward-slurp-sexp
        sp-backward-delete-char
        sp-backward-down-sexp
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-splice-sexp
        sp-up-sexp
        transpose-sexps
        zop-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        ))
